// <auto-generated />
using System;
using LifeGrid.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeGrid.Infrastructure.Migrations
{
    [DbContext(typeof(LifeGridDbContext))]
    [Migration("20260617184433_AddGoalRefinementAnswerSchemaAndSessionStagingFields")]
    partial class AddGoalRefinementAnswerSchemaAndSessionStagingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LifeGrid.Domain.Goal.Goal", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbientTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Onboarding.OnboardingSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawGoalDraft")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefinementQuestionsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatedGoalJson")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("OnboardingProgressCache", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Goal.Goal", b =>
                {
                    b.HasOne("LifeGrid.Domain.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LifeGrid.Domain.Goal.GoalRefinementAnswer", "RefinementAnswers", b1 =>
                        {
                            b1.Property<Guid>("RefinementAnswerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Answer")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("RankOrder")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RefinementAnswerId");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalRefinementAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsMany("LifeGrid.Domain.Goal.LinkedBadHabit", "LinkedBadHabits", b1 =>
                        {
                            b1.Property<Guid>("BadHabitId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DangerLevel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BadHabitId");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalLinkedBadHabits", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.Navigation("LinkedBadHabits");

                    b.Navigation("RefinementAnswers");
                });

            modelBuilder.Entity("LifeGrid.Domain.Onboarding.OnboardingSession", b =>
                {
                    b.HasOne("LifeGrid.Domain.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LifeGrid.Domain.UserProfile.UserProfile", b =>
                {
                    b.OwnsMany("LifeGrid.Domain.UserProfile.UserBadge", "Badges", b1 =>
                        {
                            b1.Property<Guid>("BadgeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BadgeType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DateEarned")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BadgeId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserBadges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LifeGrid.Domain.UserProfile.UserActiveStates", "ActiveStates", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DoubleXpExpiry")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("DoubleXpMode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserActiveStates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("LifeGrid.Domain.UserProfile.UserEconomy", "Economy", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CurrentSp")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LifetimeGpAverage")
                                .HasColumnType("REAL");

                            b1.Property<int>("LifetimeXp")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxShieldCap")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShieldsAvailable")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserEconomy", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.Navigation("ActiveStates")
                        .IsRequired();

                    b.Navigation("Badges");

                    b.Navigation("Economy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
