// <auto-generated />
using System;
using LifeGrid.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeGrid.Infrastructure.Migrations
{
    [DbContext(typeof(LifeGridDbContext))]
    [Migration("20260622213718_Phase20_AddHabitCompletionLogs")]
    partial class Phase20_AddHabitCompletionLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LifeGrid.Domain.Goal.Goal", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbientTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Habit.CompletedValueLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ActualValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitCompletionLogs", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Habit.Habit", b =>
                {
                    b.Property<Guid>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadlineDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WeekGoalId")
                        .HasColumnType("TEXT");

                    b.HasKey("HabitId");

                    b.HasIndex("WeekGoalId");

                    b.ToTable("Habits", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Onboarding.OnboardingSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueprintJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChosenStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawGoalDraft")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefinementAnswersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefinementQuestionsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatedGoalJson")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("OnboardingProgressCache", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceSurveyCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Week.Week", b =>
                {
                    b.Property<Guid>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWeeklySpEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeekId");

                    b.ToTable("Weeks", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.WeekGoal.WeekGoal", b =>
                {
                    b.Property<Guid>("WeekGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<double>("GoalWeeklyGp")
                        .HasColumnType("REAL");

                    b.Property<int>("GoalWeeklyXpEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PenaltyState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekGoalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("TEXT");

                    b.HasKey("WeekGoalId");

                    b.HasIndex("WeekId");

                    b.ToTable("WeekGoals", (string)null);
                });

            modelBuilder.Entity("LifeGrid.Domain.Goal.Goal", b =>
                {
                    b.HasOne("LifeGrid.Domain.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LifeGrid.Domain.Goal.GoalRefinementAnswer", "RefinementAnswers", b1 =>
                        {
                            b1.Property<Guid>("RefinementAnswerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Answer")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("RankOrder")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RefinementAnswerId");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalRefinementAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsMany("LifeGrid.Domain.Goal.LinkedBadHabit", "LinkedBadHabits", b1 =>
                        {
                            b1.Property<Guid>("BadHabitId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DangerLevel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BadHabitId");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalLinkedBadHabits", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.Navigation("LinkedBadHabits");

                    b.Navigation("RefinementAnswers");
                });

            modelBuilder.Entity("LifeGrid.Domain.Habit.CompletedValueLog", b =>
                {
                    b.HasOne("LifeGrid.Domain.Habit.Habit", null)
                        .WithMany("CompletedValuesLog")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeGrid.Domain.Habit.Habit", b =>
                {
                    b.HasOne("LifeGrid.Domain.WeekGoal.WeekGoal", null)
                        .WithMany()
                        .HasForeignKey("WeekGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeGrid.Domain.Onboarding.OnboardingSession", b =>
                {
                    b.HasOne("LifeGrid.Domain.UserProfile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LifeGrid.Domain.UserProfile.UserProfile", b =>
                {
                    b.OwnsMany("LifeGrid.Domain.UserProfile.UserBadge", "Badges", b1 =>
                        {
                            b1.Property<Guid>("BadgeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BadgeType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DateEarned")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("BadgeId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserBadges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("LifeGrid.Domain.UserProfile.UserActiveStates", "ActiveStates", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DoubleXpExpiry")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("DoubleXpMode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserActiveStates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("LifeGrid.Domain.UserProfile.UserEconomy", "Economy", b1 =>
                        {
                            b1.Property<Guid>("UserProfileUserId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CurrentSp")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("LifetimeGpAverage")
                                .HasColumnType("REAL");

                            b1.Property<int>("LifetimeXp")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxShieldCap")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ShieldsAvailable")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UserEconomy", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.Navigation("ActiveStates")
                        .IsRequired();

                    b.Navigation("Badges");

                    b.Navigation("Economy")
                        .IsRequired();
                });

            modelBuilder.Entity("LifeGrid.Domain.WeekGoal.WeekGoal", b =>
                {
                    b.HasOne("LifeGrid.Domain.Week.Week", null)
                        .WithMany("WeekGoals")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeGrid.Domain.Habit.Habit", b =>
                {
                    b.Navigation("CompletedValuesLog");
                });

            modelBuilder.Entity("LifeGrid.Domain.Week.Week", b =>
                {
                    b.Navigation("WeekGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
