// <auto-generated />
using System;
using LifeGrid.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeGrid.Infrastructure.Migrations
{
    [DbContext(typeof(LifeGridDbContext))]
    [Migration("20260617121203_InitialOnboardingSchema")]
    partial class InitialOnboardingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LifeGrid.Domain.Onboarding.OnboardingSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawGoalDraft")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.ToTable("OnboardingProgressCache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
